#! /bin/sh

# USB Gadget for ORION hardware
#
# Copyright (C) 2021 Vadym Fylypenko <vfilippenko@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

#if [ ! -d /sys/kernel/config/usb_gadget ]; then
#        modprobe libcomposite
#fi

#if [ -d /sys/kernel/config/usb_gadget/orionusb ]; then
#        exit 0
#fi

g="/sys/kernel/config/usb_gadget/oriondev"

usb_ver="0x0200" # USB 2.0
dev_class="0xEF" #
dev_subclass="0x04" #
vid="0x1b67" #
pid="0x400c" #
device="0x3000" # this should be incremented any time there are breaking changes
                # to this script so that the host OS sees it as a new device and
                # re-enumerates everything rather than relying on cached values
mfg="KEPM" # KEPM firmware
prod="ORION" # 
cfg1="RNDIS"
#speed="high-speed"

ms_vendor_code="0xcd" # Microsoft
ms_qw_sign="MSFT100" # also Microsoft (if you couldn't tell)
ms_compat_id="RNDIS" # matches Windows RNDIS Drivers
ms_subcompat_id="5162001" # matches Windows RNDIS 6.0 Driver

# Create a new gadget

mkdir ${g}
echo "${usb_ver}" > ${g}/bcdUSB
echo "${dev_class}" > ${g}/bDeviceClass
echo "${dev_subclass}" > ${g}/bDeviceSubClass
echo "${vid}" > ${g}/idVendor
echo "${pid}" > ${g}/idProduct
echo "${device}" > ${g}/bcdDevice
    
mkdir ${g}/strings/0x409
echo "${mfg}" > ${g}/strings/0x409/manufacturer
echo "${prod}" > ${g}/strings/0x409/product
#echo "${serial}" > ${g}/strings/0x409/serialnumber

# Create configuration for RNDIS.

mkdir ${g}/configs/c.1
#echo "${speed}" > ${g}/configs/c.1/maximum_speed
mkdir ${g}/configs/c.1/strings/0x409
echo "${cfg1}" > ${g}/configs/c.1/strings/0x409/configuration 

# On Windows 7 and later, the RNDIS 5.1 driver would be used by default,
# but it does not work very well. The RNDIS 6.0 driver works better. In
# order to get this driver to load automatically, we have to use a
# Microsoft-specific extension of USB.

echo "1" > ${g}/os_desc/use
echo "${ms_vendor_code}" > ${g}/os_desc/b_vendor_code
echo "${ms_qw_sign}" > ${g}/os_desc/qw_sign

# Create the RNDIS function, including the Microsoft-specific bits

mkdir ${g}/functions/rndis.usb0
echo "${ms_compat_id}" > ${g}/functions/rndis.usb0/os_desc/interface.rndis/compatible_id
echo "${ms_subcompat_id}" > ${g}/functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id

# Link configs and bind the USB device

ln -s ${g}/functions/rndis.usb0 ${g}/configs/c.1
ln -s ${g}/configs/c.1 ${g}/os_desc
echo ci_hdrc.0 > ${g}/UDC

exit 0

